name = "MyFirstPkg"
uuid = "1691fe09-05ca-4f98-b83c-0a332c4e192b"
authors = ["Cai"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
